#!/usr/bin/env bash

# check docker image for building
if [ "$(docker images -q httpp-bld:16.04 2> /dev/null)" == "" ]; then
  echo "Build Docker image as httpp-bld:16.04"
  docker image build --compress -t httpp-bld:16.04 -f ./Dockerfile.bld .
fi

# create install dir
mkdir -p appins 

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`/appins:/appins -v `pwd`:`pwd` -w `pwd` -i -t httpp-bld:16.04 $@
else
  echo "Enter shell ..."
  docker run -v `pwd`/appins:/appins -v `pwd`:`pwd` -w `pwd` -i -t httpp-bld:16.04
fi
