#!/usr/bin/env bash

# check build docker image
if [ "$(docker images -q httpp:16.04 2> /dev/null)" == "" ]; then
  echo "Build Docker image as httpp:16.04"
  docker image build --compress -t httpp:16.04 .
fi

# execute commands 
echo "$@ ..."
docker run -v `pwd`:`pwd` -w `pwd` -i -t httpp:16.04 $@

