#!/usr/bin/env bash

# check build docker image
if [ "$(docker images -q httpp-bld:16.04 2> /dev/null)" == "" ]; then
  echo "Build Docker image as httpp-bld:16.04"
  docker image build --compress -t httpp-bld:16.04 -f ./Dockerfile.bld .
fi

# create install dir
mkdir -p appins 

# execute commands 
echo "$@ ..."
docker run -v `pwd`/appins:/appins -v `pwd`:`pwd` -w `pwd` -i -t httpp-bld:16.04 $@

