#!/usr/bin/env bash

# check docker image for packaging 
if [ "$(docker images -q httpp:16.04 2> /dev/null)" == "" ]; then
  echo "Build Docker image as httpp:16.04"
  docker image build --compress -t httpp:16.04 -f ./Dockerfile.pkg ./appins
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  httpp:16.04 $@
else
  echo "Enter Node.js repl ..."
  docker run                         -i -t \
  --rm --network host \
  httpp:16.04
fi
