#!/usr/bin/env bash

# check docker image for packaging
if [ $# == 0 ]; then
  echo "Build Docker image as httpp:0.8"
  docker image build --compress -t httpp:0.8 -t httpp:16.04 -f ./Dockerfile.pkg ./appins
fi

if [ "$(docker images -q httpp:0.8 2> /dev/null)" == "" ]; then
  echo "Build Docker image as httpp:0.8"
  docker image build --compress -t httpp:0.8 -t httpp:16.04 -f ./Dockerfile.pkg ./appins
fi

# execute commands 
if [ $# -ne 0 ]; then
  echo "$@ ..."
  docker run -v `pwd`:`pwd` -w `pwd` -i -t \
  --rm --network host \
  httpp:0.8 $@
else
  echo "Enter Node.js repl ..."
  docker run                         -i -t \
  --rm --network host \
  httpp:0.8
fi
