#
# node-httpp packaging Dockerfile
#
# https://github.com/InstantWebP2P/node-httpp
#

# Pull base image.
FROM ubuntu:16.04

# Install.

# Add files.
COPY . /appins/

# Set environment variables.
ENV HOME /root
ENV PATH /appins/bin:$PATH
ENV LD_LIBRARY_PATH /appins/lib:$LD_LIBRARY_PATH

# Update npm
RUN \
  npm config set strict-ssl false -g && \
  npm i npm@3.10.10 -g

# Define working directory.
WORKDIR /data

# Define default command.
CMD ["node"]
