#
# node-httpp packaging Dockerfile
#
# https://github.com/InstantWebP2P/node-httpp
# Copyright (c) 2020 Tom Zhou<iwebpp@gmail.com>


# Pull base image.
FROM ubuntu:16.04

# Install.

# Add files.
COPY . /appins/

# Set environment variables.
ENV HOME /root
ENV PATH /appins/bin:$PATH
ENV LD_LIBRARY_PATH /appins/lib:$LD_LIBRARY_PATH

# Install es6-shim 
RUN \
  npm i es6-shim@0.35.5 -g --only=production

# Define working directory.
WORKDIR /appins

# Define default command.
CMD ["node"]
