name: build-macOS

on:
  push:
    branches: [ v0.8-httpp ]
  pull_request:
    branches: [ v0.8-httpp ]

env:
  PYTHON_VERSION: 2.7
  FLAKY_TESTS: dontcare

jobs:
  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make -j8 V=1
